version: "3"

services:
  bitrix_app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/
    container_name: bitrix_app
    depends_on:
      - bitrix_db
  bitrix_db:
    image: mysql:5.7
    restart: always
    user: 1000:1000
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: bitrix
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8082:3306"
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    container_name: bitrix_db
  bitrix_phpmyadmin:
    image: phpmyadmin
    ports:
      - "8083:80"
    container_name: bitrix_phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: bitrix_db
      PMA_USER: root
      PMA_PASSWORD: root
